[build]
publish = "public"
command = ""
[build.environment]
  NODE_VERSION = "20.19.4"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "http://*mvppainting.netlify.app/*"
  to = "https://mvppainting.netlify.app/:splat"
  status = 301
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

